language: android
before_script:
- openssl aes-256-cbc -K $encrypted_5559c6579f6a_key -iv $encrypted_5559c6579f6a_iv
  -in onemdm.keystore.enc -out onemdm.keystore -d
- cp src/main/java/com/multunus/one_mdm_client/Config.java.template src/main/java/com/multunus/one_mdm_client/Config.java
script: "./gradlew clean build"
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.1.0
  - android-18
env:
  global:
  - secure: N8kn4yC8W/i7hDw51fHwqStmoemT3srPjthyCvmFdpMhCQm9IRk+UAJ3XbmqVPiF2AcfYrSXAgI4sdTUs5+7xm5OCEWiBJ5ra95Y9FxUO5D+QJRFjQqgAO7uh1vHJjsOVSXDbVfntZt4fKVt4n1sqv5iSbxLjmcx60Zm76HlhKc=
  - secure: V8ztPMU+aI9Ah33L0n6lMYiGi7XT77kD9Eis+jlfy3uF7uftcZ7cqrqHjcsWCMPhx7cT2uEh1vaBrNrj5JuN29LMtaRezVpTJMEuRPPiTLenZ/0jHdnMSNU+rtBAncBPA7RGkj/4+liejAD9/9gn9Nt0uLYd4goGQ3dJ6jhSBOo=
  - secure: Id6fRsCrtOoX9TCEQIU1JxYKwvttU5ymYc1NHskCSW6fhGe+vznyZ6XWmEtWhp0EGQmCw7uNyIAqHMe4MP7mzlYTo7YyctCKNjvOtcv864GbONeyaj+/pLdflPHqqXTzwa09rD0sybfmhstuDzs7Czd8XhlQFaweZabKaPOOV1E=
  - secure: ZYQ+UnfJ7hqVh1ymXMNp+b5aYyV+UzZLdCwyigrFooPjWsqxG0tpScciwx2saa4httHIU+xO2rWGF2+igdMNMjI7s1td8vRbyNMymsd1tgwst6/0Gk2xnkPo8GcZvnhjuEM5ey+xh2m4l+j0+NZ3i/vegEsr4gXbVzCVH34Pzd0=
