language: android
before_script:
  - openssl aes-256-cbc -K $encrypted_5559c6579f6a_key -iv $encrypted_5559c6579f6a_iv
  -in onemdm.keystore.enc -out onemdm.keystore -d
  - cp src/main/java/com/multunus/one_mdm_client/Config.java.template src/main/java/com/multunus/one_mdm_client/Config.java
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add version.properties
  - git commit -m "Update version.properties"
  - git push origin master
script: "./gradlew clean build"
android:
  components:
  - platform-tools
  - tools
  - build-tools-19.1.0
  - android-18
env:
  global:
  - secure: N8kn4yC8W/i7hDw51fHwqStmoemT3srPjthyCvmFdpMhCQm9IRk+UAJ3XbmqVPiF2AcfYrSXAgI4sdTUs5+7xm5OCEWiBJ5ra95Y9FxUO5D+QJRFjQqgAO7uh1vHJjsOVSXDbVfntZt4fKVt4n1sqv5iSbxLjmcx60Zm76HlhKc=
  - secure: V8ztPMU+aI9Ah33L0n6lMYiGi7XT77kD9Eis+jlfy3uF7uftcZ7cqrqHjcsWCMPhx7cT2uEh1vaBrNrj5JuN29LMtaRezVpTJMEuRPPiTLenZ/0jHdnMSNU+rtBAncBPA7RGkj/4+liejAD9/9gn9Nt0uLYd4goGQ3dJ6jhSBOo=
  - secure: Id6fRsCrtOoX9TCEQIU1JxYKwvttU5ymYc1NHskCSW6fhGe+vznyZ6XWmEtWhp0EGQmCw7uNyIAqHMe4MP7mzlYTo7YyctCKNjvOtcv864GbONeyaj+/pLdflPHqqXTzwa09rD0sybfmhstuDzs7Czd8XhlQFaweZabKaPOOV1E=
  - secure: ZYQ+UnfJ7hqVh1ymXMNp+b5aYyV+UzZLdCwyigrFooPjWsqxG0tpScciwx2saa4httHIU+xO2rWGF2+igdMNMjI7s1td8vRbyNMymsd1tgwst6/0Gk2xnkPo8GcZvnhjuEM5ey+xh2m4l+j0+NZ3i/vegEsr4gXbVzCVH34Pzd0=
  - secure: XIexDWDnOYYECZIc9uuqDuAIwxDeMPizgzRf9dYQUPQFlSa20K1xidX7qBJ3e6LHPtJkoE56UJNs/qU809Zb5EYHFItJIp6gBGZR3IbHOg5nmKhFvnFI9plmtBUR86/lRehYIZ4RcWGpXQ54dwBl49EyuFyfkukBdGOhsLj/5kI=
  - secure: JCnopp0OCEh1WLoau17m84RRjbnhI0BF/LoI9EJeNft319BqlLQbQBm0T784k/0OFET6GcBYKVqbWBqUBvWavC0Y6Um70z3dYnsTLlMd52bwkkjzWbhaLaZ5a9HLBRM2KcZhVbsds1Kg3pIjW67YtrElVjSal+bxCvKvuoVbxdg=
  - secure: L7pO0nVr+rtEQ0pUeurWrF+vv6H7/16xlfiTetKYbBY3U+ylZJmGueipgBK+ONR7YyoNmQH2ARgmoTaT5oDUbYq+WA6H8Iif3JHFJs+/8Il3zHnBcsjhjIA4yA9TY5+59Uo34eO4UEZ4ynQsQNlFeacCSWpicbQJx486E9SDHgc=
before_install:
- openssl aes-256-cbc -K $encrypted_5559c6579f6a_key -iv $encrypted_5559c6579f6a_iv
  -in onemdm.keystore.enc -out onemdm.keystore -d

